In [1]:
import numpy as np

In [2]:
# Creating a Numpy Array

In [3]:
my_list = [1,2,3]

In [5]:
x = np.array(my_list)

In [6]:
type(x)

numpy.ndarray

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [10]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [14]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [15]:
type(1)

int

In [16]:
type(1.0)

float

In [17]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [18]:
np.ones(1)

array([ 1.])

In [19]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [21]:
np.linspace(0,10,30)

array([  0.        ,   0.34482759,   0.68965517,   1.03448276,
         1.37931034,   1.72413793,   2.06896552,   2.4137931 ,
         2.75862069,   3.10344828,   3.44827586,   3.79310345,
         4.13793103,   4.48275862,   4.82758621,   5.17241379,
         5.51724138,   5.86206897,   6.20689655,   6.55172414,
         6.89655172,   7.24137931,   7.5862069 ,   7.93103448,
         8.27586207,   8.62068966,   8.96551724,   9.31034483,
         9.65517241,  10.        ])

In [22]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [26]:
np.random.rand(2,3)

array([[ 0.50275165,  0.98207665,  0.07906847],
       [ 0.30968254,  0.67870389,  0.7650727 ]])

In [28]:
np.random.randn(5,4)

array([[-0.28503436,  1.0902202 , -1.59853158,  0.90750833],
       [ 1.9133821 ,  0.56990256,  0.34137101, -0.05827532],
       [ 0.08999762, -0.39998117,  1.23270895,  1.89591506],
       [-0.83279612, -0.13078847,  1.96129916, -1.2416697 ],
       [-0.55035551,  0.59723737, -2.10525068,  0.01999977]])

In [30]:
np.random.randint(1,31,100)

array([ 9, 29, 25,  2, 18, 19,  9, 18, 29,  7, 24, 11, 10, 23,  6, 23, 18,
       17, 23, 17, 24,  2, 14, 19, 12, 10,  7,  3, 20, 17, 15,  3, 24, 13,
        2, 15, 15, 16, 29, 15, 27, 13, 15, 23, 15, 19, 12, 22,  4, 12, 21,
       26, 16, 20,  9, 18, 18, 21, 21, 21,  3, 27,  5,  9,  7, 24, 20,  6,
       28,  7,  6,  4, 22, 14,  2, 29,  9, 24,  4, 12,  8, 14, 27, 18,  7,
       20, 26, 26, 14, 20, 14,  6, 18, 15, 21, 25, 11, 22, 27,  3])

In [33]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr.shape

(25,)

In [39]:
arr.reshape(5,5).shape

(5, 5)

In [40]:
arr.dtype

dtype('int64')

In [41]:
ranarr

array([29, 26,  2, 41, 12, 22, 19,  2, 39,  3])

In [42]:
ranarr.max()

41

In [43]:
ranarr.argmax()

3

In [44]:
arr = np.arange(0,10)

In [45]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [48]:
arr/arr

/Users/mohit.thakral/anaconda3/envs/pyfinance/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [49]:
1/arr

/Users/mohit.thakral/anaconda3/envs/pyfinance/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111])

In [50]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [51]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [52]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [53]:
arr.sqrt()

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [54]:
arr.sum()

45

In [55]:
arr = np.arange(0,11)

In [56]:
arr[8]

8

In [58]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr[1:4]

array([1, 2, 3])

In [61]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])